language: python
cache: pip
python:
 - '2.7'
 - '3.4'
 - '3.5'
 - '3.6'
 - '3.7-dev'

matrix:
    fast_finish: true
    include:
      - python: '2.7'
        env: TOXENV=flake8
      - python: '3.6'
        env: DRF=master

    allow_failures:
      - env: TOXENV=flake8
      - env: DRF=master
      - python: '2.7'
      - python: '3.7'

install:
 - pip install -r requirements_dev.txt

before_script:
 - coverage erase

script:
 - tox

after_success:
 - codecov

branches:
  only:
    - master
