language: python
python: 3.6
os: linux
dist: xenial

jobs:
  include:
    - stage: lint
      script: scripts/lint.sh
      install:
        - pip install .[lint]

    # Use aliases to specify matrix style parallelism in this stage only
    - &unittest
      stage: unittest
      python: 2.7
      script: scripts/tox-filter.sh py27
      install:
        - pip install .[tests]

    - <<: *unittest
      python: 3.6
      script: scripts/tox-filter.sh py36

    - <<: *unittest
      python: 3.7
      script: scripts/tox-filter.sh py37

    - <<: *unittest
      python: 3.8
      script: scripts/tox-filter.sh py38

    # This ensures that readthedocs will be able to build the docs
    - stage: test-docs
      script: scripts/docs.sh
      install:
        - pip install .[docs]

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: joellefkowitz
  password:
    secure: fbaBrbBl6mJf54iV2LR/wskFZRGn1ftlgt+BCCGsdF2eDrASnQaszS/IM4PXd4bsUalAPcxcbGC0lEAqiDgZneKlSYvHps1oy6ypymq7JLHKW/iQ3bBeXvT2QEaUgg5LqjX2CIlhSgiY2mVa6gQt1BwlutJatM3sJ6yvBQu+3vVWpwWohfTqjPmt1FdR9WWz5/sviDFyHYnGSRmgQUkcyfnKHZ4/UtEiLynVC1RVNzb+aAOCp2M2lW+A2SBiKMISzbkvgL/pO9f8ceHInUhY+oZJ/wzMa1hyF+Dlo7ut3LywFNrFdheP5r/1lTusR5UYXKncsiCLCyRujal8hOAnUaHkP+XGm+QLULKOGG2qkxmasO7lRXSbYgQGEGoKQNsiwjqJN3AbofIL1FIw/2IYFia/bkvhZCyBLUAHoCJ0BgNF/kvYBDzBDR2b6r8GjG2OREL+tkgAAsHauRgYKfkP738Qqj8UEnQ+Xrtnm+zOw86AuYD4xx3DHS2qAzsnhEs4nVp6WvLSB4PqOzzLZmG73zQZgKTTGIs7kgtnIZBR+3gIQCFIUAaeV9rzNmED0eKt8qLtC4gXFLx5aqzM2hOnuuKII+Ueiz8ZPbjFXrE7VmpCr0KfJaxu4UcqgSjJY5OI9f3EGJsJIC7O1fkrNCNPH0UUTZM0fM9OlxUNPs8qp1I=
  on:
    branch: master
    tags: true
